name: 'Statsig Github SDK'
description: 'Statsig SDK for github actions'

author: 'kenny-statsig'

inputs:
  sdk-key:
    description: 'Statsig server SDK key'
    required: true
    default: ''
  user:
    description: 'User JSON to use for evaluating'
    required: true
    default: ''
  environment:
    description: 'Statsig environment tier'
    required: false
    default: ''
  log-exposures:
    description: 'Whether or not to log exposures. Default: false'
    required: false
    default: 'false'
  gates:
    description: ':ist of feature gates to evaluate separated by new line'
    required: false
    default: ''
  configs:
    description: 'List of dynamic configs to evaluate separated by new line'
    required: false
    default: ''
  experiments:
    description: 'List of experiments to evaluate separated by new line'
    required: false
    default: ''
  events:
    description: 'List of events to evaluate separated by new line'
    required: false
    default: ''

runs:
  using: 'node16'
  main: 'dist/index.js'
